### Site info:
title: Akshay Suthar
tagline: Arch Linux, Network Administrator, Penetration Tester and Security Professional
author: Akshay Suthar
email: akshay.suthar@gmail.com
description: "Freshman21 is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme, Freshman21"
#baseurl: "/freshman21" # the subpath of your site, e.g. /blog/
url: "http://akshaysth.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: akshaysth
github_username: akshaysth
#disqus_shortname: freshman21
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Akshay Suthar. I'm a network administration, penetration testing and security professional. Enjoy! # these are shown on aboutme-sidebar.
aboutme_photo: https://www.dropbox.com/s/348ux8wjhsei5pt/profile.png?dl=0 # your photo.
google_analytics_key: UA-62769445-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Akshay Suthar
        href: http://akshaysth.github.io
        title: Akshay Suthar's Blog
      - name: Akshay Suthar Photography
        href: http://www.akshaysuthar.com/
        title: Akshay Suthar Photography

### Build settings
markdown: kramdown
### highlighter: pygments
highlighter: rouge
paginate: 5
excerpt_separator: <!-- more -->
